### ISSUE TITLE
Getting the data

### ISSUE THREAD

**Issue by SanduIrina** [ugis22/music_recommender#3]
Hello, are there any other csv files from millionsongdataset we can use with this? I am interested in csv files containing a larger number of unique songs.

**Comment by ugis22** [comment]
Hi, Sorry for the delay in answering you. The songs from [millonsongdataset](http://millionsongdataset.com/pages/getting-dataset/) you can get it from: If not, you can try the [Spotify dataset](https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks)
