### ISSUE TITLE
ValueError: Unstacked DataFrame is too big, causing int32 overflow

### ISSUE THREAD

**Issue by ravikumarmn** [ugis22/music_recommender#4]
Can you please tell me, How to solve this?

**Comment by SudhaMsr** [comment]
yes. I am getting the same error..

**Comment by ugis22** [comment]
Hi 👋 , which code are you running? In which part are you getting this error? Can you guide me on that so I can help you?

**Comment by ravikumarmn** [comment]
Thanks For Replying. Due to the high load of data, my laptop was giving me this error:  **[ValueError: Unstacked DataFrame is too big, causing int32 overflow #4](https://github.com/ugis22/music_recommender/issues/4)**.

 Now it is resolved. Thanks once again ugis22.
